## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    #- "branch-*.md"   # branch management
    #- "commit-*.md"   # commit conventions
    #- "pr-*.md"       # pull request workflow
    #- "merge-*.md"    # merge strategy
    #- "tag-*.md"      # tagging strategy
    #- "release-*.md"  # release strategy
    # group the remainding '*.md' files using the glob pattern
    - "*.md"

ignore:
    # https://lukasgeiter.github.io/mkdocs-awesome-nav/features/hiding/
    - "_template.md"
    #- hidden/
    - "*.hidden.md"

append_unmatched: true
