# Note for future reference... CAN NOT deploy GitHub Pages in a **personal account** for a **private repo** without paying for the account upgrade, which is $48 per year.
# https://www.mkdocs.org/user-guide/configuration/
site_name: rwaight on GitHub pages
site_url: https://rwaight.github.io/
site_author: rwaight
repo_url: https://github.com/rwaight/rwaight.github.io
repo_name: rwaight/rwaight.github.io
# make sure to update the `plugins:git-committers:repository` value to match the `repo_name` value

## use https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin for navigation
## the plugin won't do anything if `mkdocs.yml` defines a `nav` or `pages` entry
## https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin?tab=readme-ov-file#customize-navigation
## use https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin for navigation
# # https://www.mkdocs.org/user-guide/configuration/#nav
# # https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
# nav:
#   - Home: 'index.md'
#   - Blog:
#     - blog/index.md
#     # If you do have a navigation defined then you need to add the blog index page only to it.
#     # You need not and should not add the individual blog posts.
#     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#built-in-blog-plugin
#   - Guides:
#     - guides/
#   - Random:
#     - random/
## use https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin for navigation
## https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin?tab=readme-ov-file#customize-navigation

# https://www.mkdocs.org/user-guide/configuration/#theme
theme:
  name: material
  #locale: en
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    # https://squidfunk.github.io/mkdocs-material/plugins/blog/#navigation
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    #
  icon:
    # # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/?h=icon#favicon
    # favicon: 
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/?h=icon#logo
    logo: simple/github
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/git-alt
    #repo: octicons/mark-github-24
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    edit: material/pencil 
    view: material/eye
    #
  language: en    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette
    scheme: slate

# https://www.mkdocs.org/user-guide/configuration/#docs_dir
docs_dir: 'docs'

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/

# # Reserved for future use, see https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/
# #                          and https://github.com/jimporter/mike#usage
### WARNING: Implementing versioning will require a lot of extra work to get started using GitHub actions and workflows
# extra:
#   version:
#     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#configuration
#     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#usage
#     provider: mike
#     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning
#     # be sure to override the `outdated` block
#     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#setting-a-default-version
### WARNING: Implementing versioning will require a lot of extra work to get started using GitHub actions and workflows


markdown_extensions:
  # https://python-markdown.github.io/extensions/attr_list/
  # `attr_list` use: 'attr_list'
  #    # setup
  #    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#betterem
  # https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem
  # # https://oprypin.github.io/markdown-callouts/index.html#markdown-callouts
  # # will need to install with 'pip install markdown-callouts' in 'publish.yml'
  # - callouts
  ###
  # not sure if 'pymdownx.github' works
  #- pymdownx.github
  # https://squidfunk.github.io/mkdocs-material/reference/lists/
  # `lists` use: 'def_list' and 'pymdownx.tasklist' ('custom_checkbox: true' within 'pymdownx.tasklist')
  #    # setup
  #    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#definition-lists
  - def_list
    # https://squidfunk.github.io/mkdocs-material/reference/lists/#configuration
  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-task-lists
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tasklist
  - pymdownx.tasklist:
      # 'custom_checkbox: true' is used with 'lists'
      custom_checkbox: true
  - toc:
      title: On this page
      permalink: true
  # https://squidfunk.github.io/mkdocs-material/reference/formatting/#configuration
  # support for sub and superscripts
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets
  - pymdownx.snippets


# https://www.mkdocs.org/user-guide/configuration/#plugins
plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin
  - privacy
  # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - awesome-pages
  - search
  # https://squidfunk.github.io/mkdocs-material/plugins/blog/
  - blog:
      # https://squidfunk.github.io/mkdocs-material/plugins/blog/#general
      enabled: true
      blog_dir: blog
      blog_toc: true
      # https://squidfunk.github.io/mkdocs-material/plugins/blog/#posts
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/
  - tags:
      enabled: true
      # https://squidfunk.github.io/mkdocs-material/plugins/tags/#config.tags_file
      # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/102
      tags_file: plugins/tags.md
      # # https://squidfunk.github.io/mkdocs-material/plugins/tags/?h=tags+allowed#config.tags_allowed
      # # 'tags_allowed' is for sponsors only
      # tags_allowed:
      #   - GitHub
      #   - Jekyll
      #   - Linux
      #   - MacOS
      #   - MkDocs
      #   - Virtualization
      # # https://squidfunk.github.io/mkdocs-material/plugins/tags/?h=tags+allowed#config.tags_hierarchy
      # # 'tags_hierarchy' is for sponsors only
      # tags_hierarchy: true
      # By default, tags are separated by a forward slash `/`, but you can change this to any string, e.g., `.`
      # https://squidfunk.github.io/mkdocs-material/plugins/tags/#config.tags_hierarchy_separator
  - macros:
      # https://mkdocs-macros-plugin.readthedocs.io/en/stable/
      include_dir: includes
      # 
      # https://mkdocs-macros-plugin.readthedocs.io/en/latest/rendering/#solution-2-opt-in-specify-which-pages-must-be-rendered
      render_by_default: false
  - git-revision-date-localized:
      # https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/index.html
      # https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/
      enable_creation_date: true
      # type: iso_datetime              # default is 'date'
      exclude:
        - index.md
      fallback_to_build_date: true
  - git-committers:
      # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
      # https://github.com/ojacques/mkdocs-git-committers-plugin-2
      repository: rwaight/rwaight.github.io
      branch: main
      exclude:
        - index.md
        - test-*.md
