# https://www.mkdocs.org/user-guide/configuration/
site_name: rwaight on GitHub pages
site_url: https://rwaight.github.io/
repo_url: https://github.com/rwaight/rwaight.github.io
repo_name: rwaight/rwaight.github.io

# https://www.mkdocs.org/user-guide/configuration/#nav
nav:
  - 'index.md'
  - 'setup-github-pages.md'
  - Blog:
    - blog/index.md

# https://www.mkdocs.org/user-guide/configuration/#theme
theme:
  name: material
  #locale: en
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  icon:
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/git-alt
  language: en    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette
    scheme: slate

# https://www.mkdocs.org/user-guide/configuration/#docs_dir
docs_dir: 'docs'

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/

# https://www.mkdocs.org/user-guide/configuration/#plugins
plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin
  - privacy
  # https://squidfunk.github.io/mkdocs-material/plugins/blog/
  - blog:
      # https://squidfunk.github.io/mkdocs-material/plugins/blog/#general
      enabled: true
      blog_dir: blog
      blog_toc: true
      # https://squidfunk.github.io/mkdocs-material/plugins/blog/#posts
