# https://www.mkdocs.org/user-guide/configuration/
site_name: rwaight on GitHub pages
site_url: https://rwaight.github.io/
repo_url: https://github.com/rwaight/rwaight.github.io
repo_name: rwaight/rwaight.github.io

# https://www.mkdocs.org/user-guide/configuration/#nav
# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Home: 'index.md'
  - Blog:
    - blog/index.md
    # If you do have a navigation defined then you need to add the blog index page only to it.
    # You need not and should not add the individual blog posts.
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#built-in-blog-plugin
  #- Guides: 'guides/'
  #- Random: 'random/'

# https://www.mkdocs.org/user-guide/configuration/#theme
theme:
  name: material
  #locale: en
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
  icon:
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/git-alt
  language: en    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette
    scheme: slate

# https://www.mkdocs.org/user-guide/configuration/#docs_dir
docs_dir: 'docs'

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#betterem
  # https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem
  # # https://oprypin.github.io/markdown-callouts/index.html#markdown-callouts
  # # will need to install with 'pip install markdown-callouts' in 'publish.yml'
  # - callouts
  ###
  # not sure if 'pymdownx.github' works
  #- pymdownx.github
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#definition-lists
  #- def_list
  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # https://squidfunk.github.io/mkdocs-material/reference/lists/#using-task-lists
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tasklist
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      title: On this page
      permalink: true

# https://www.mkdocs.org/user-guide/configuration/#plugins
plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin
  - privacy
  # https://squidfunk.github.io/mkdocs-material/plugins/blog/
  - blog:
      # https://squidfunk.github.io/mkdocs-material/plugins/blog/#general
      enabled: true
      blog_dir: blog
      blog_toc: true
      # https://squidfunk.github.io/mkdocs-material/plugins/blog/#posts
