## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    # group the remainding '*.md' files using the glob pattern
    - "*.md"
    - References:
        - MkDocs (Local): ../../references/mkdocs/
        - MkDocs (Official): https://www.mkdocs.org/
        - Material for MkDocs: https://squidfunk.github.io/mkdocs-material/

append_unmatched: true

ignore:
    # https://lukasgeiter.github.io/mkdocs-awesome-nav/features/hiding/
    - "_template.md"
    #- hidden/
    - "*.hidden.md"
