# https://github.com/rwaight/rwaight.github.io/pkgs/container/rwaight.github.io%2Fmkdocs-material
FROM ghcr.io/rwaight/rwaight.github.io/mkdocs-material
# Plugins used by this site are already in the published image (container/requirements.txt).
# Site deploy in .github/workflows/publish-pages.yml still pip-installs and does not use this image.
# Add extra plugins below, for example:
# RUN pip install mkdocs-glightbox
