# https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker
FROM ghcr.io/rwaight/rwaight.github.io/mkdocs-material
# be sure to include the plugins that are installed in the 'publish-pages' workflow
#     check the '.github/workflows/publish-pages.yml' file
# Plugins used by this site are already in the published image (container/requirements.txt).
# Site deploy in .github/workflows/publish-pages.yml still pip-installs and does not use this image.
