## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin?tab=readme-ov-file#customize-navigation
nav:
    - overview.md
    - ...
