## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    - Ubiquiti Community Wiki:
        - ubntwiki
    # group the remainding '*.md' files using the glob pattern
    - "*.md"
