## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    #- Not categorized:
    #    # group the remainding '*.md' files using the glob pattern
    #    - "*.md"

#append_unmatched: true

# might need to review https://github.com/lukasgeiter/mkdocs-awesome-nav/issues/111 if the current config does not work
