## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
#    https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin?tab=readme-ov-file#hide-directory
hide: true
# https://squidfunk.github.io/mkdocs-material/plugins/tags/#config.tags_file
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/102