## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    - munchkin-short-rules.md
    - "setup-*.md"
    - bash
    - docker
    - github
    - mkdocs
    - windows
    - Not categorized:
        # group the remainding '*.md' files using the glob pattern
        - "*.md"
