## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    - munchkin-short-rules.md
    - "setup-*.md"
    - bash
    - docker
    #this did not work#- GitHub: 
    #this did not work#    - github/overview.md
    #this did not work#    - ... | github
    - github
    - mkdocs
    - windows
    #- ...
    #this did not work#- Windows:
    #this did not work#    - windows/overview.md
    #this did not work#    - ... | windows
    - Not categorized:
        # group the remainding '*.md' files using the glob pattern
        - "*.md"
