## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    #- Git: git
    - git
    - GitHub: github
    - linux
    #- OS: 
    #    - macos
    #    - windows
    - macos
    - windows
    #- UniFi: unifi
    - unifi
    - synology
    - Test: 
        - ... | test-*.md
    - Other: 
        - ...
