## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - Home: 
        - index.md
        - "index-*.md"
        - Restructure:
            - random
            - guides
        - Uncategorized:
            # group the remainding '*.md' files using the glob pattern
            - "*.md"
    - Blog:
        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#built-in-blog-plugin
        - blog/index.md
    - References: references
    - Resources: resources
    #- Random: random
    #- MkDocs-Material: https://squidfunk.github.io/mkdocs-material/
    #- Other: 
    #    - something.md
    #- ...
    #- index-summary.md

flatten_single_child_sections: true
