## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - Home: 
        #old#- ... | flat | index-*.md
        - "index-*.md"
        #old#- ...
        # group the remainding '*.md' files using the glob pattern
        - "*.md"
    - Blog: blog
    # - Blog:
        # - blog/index.md
        # # If you do have a navigation defined then you need to add the blog index page only to it.
        # # You need not and should not add the individual blog posts.
        # # https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#built-in-blog-plugin
    - Restructure:
        - random
        - guides
    - References: references
    #- Random: random
    #- MkDocs-Material: https://squidfunk.github.io/mkdocs-material/
    #- Other: 
    #    - something.md
    #- ...
    #- index-summary.md

flatten_single_child_sections: true