## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
#    https://lukasgeiter.github.io/mkdocs-awesome-nav/features/hiding/
hide: true
