# from https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
name: Publish site
run-name: Deploy mkdocs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  #id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout files from commit tree
        # Verified creator: https://github.com/marketplace/actions/checkout
        # GitHub Action for checking out a repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Configure Git Credentials for github-actions bot
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        # Verified creator: https://github.com/marketplace/actions/setup-python
        # Set up your GitHub Actions workflow with a specific version of Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - name: Cache dependencies and build outputs
        # Verified creator: https://github.com/marketplace/actions/cache
        # Cache dependencies and build outputs in GitHub Actions
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material 

      - run: mkdocs gh-deploy --force
