## use https://github.com/lukasgeiter/mkdocs-awesome-nav for navigation
## https://lukasgeiter.github.io/mkdocs-awesome-nav/features/nav/
nav:
    - index.md
    - docker
    - Not categorized:
        # group the remainding '*.md' files using the glob pattern
        - "*.md"

append_unmatched: true
